// Mocks generated by Mockito 5.4.6 from annotations
// in jourscape/test/features/gps_tracking/domain/use_cases/create_gps_coordinate_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter/material.dart' as _i8;
import 'package:fpdart/fpdart.dart' as _i4;
import 'package:jourscape/core/error/failures.dart' as _i5;
import 'package:jourscape/features/gps_tracking/domain/entities/gps_coordinate_entitiy.dart'
    as _i6;
import 'package:jourscape/features/gps_tracking/domain/repositories/gps_coordinate_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GpsCoordinateRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGpsCoordinateRepository extends _i1.Mock
    implements _i2.GpsCoordinateRepository {
  MockGpsCoordinateRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.GpsCoordinateEntity>> createCoordinate(
    _i6.GpsCoordinateEntity? coordinate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createCoordinate, [coordinate]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, _i6.GpsCoordinateEntity>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.Failure, _i6.GpsCoordinateEntity>
                  >(this, Invocation.method(#createCoordinate, [coordinate])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.GpsCoordinateEntity>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.GpsCoordinateEntity>>>
  getCoordinatesByDate(DateTime? dateTime) =>
      (super.noSuchMethod(
            Invocation.method(#getCoordinatesByDate, [dateTime]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, List<_i6.GpsCoordinateEntity>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.Failure, List<_i6.GpsCoordinateEntity>>
                  >(this, Invocation.method(#getCoordinatesByDate, [dateTime])),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.Failure, List<_i6.GpsCoordinateEntity>>
          >);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.GpsCoordinateEntity>>>
  getCoordinatesByDateRange(_i8.DateTimeRange<DateTime>? dateRange) =>
      (super.noSuchMethod(
            Invocation.method(#getCoordinatesByDateRange, [dateRange]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, List<_i6.GpsCoordinateEntity>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.Failure, List<_i6.GpsCoordinateEntity>>
                  >(
                    this,
                    Invocation.method(#getCoordinatesByDateRange, [dateRange]),
                  ),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.Failure, List<_i6.GpsCoordinateEntity>>
          >);

  @override
  _i3.Future<_i4.Either<_i5.Failure, int>> updateCoordinate(
    _i6.GpsCoordinateEntity? coordinate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateCoordinate, [coordinate]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, int>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, int>>(
                this,
                Invocation.method(#updateCoordinate, [coordinate]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, int>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, int>> deleteCoordinate(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCoordinate, [id]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, int>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, int>>(
                this,
                Invocation.method(#deleteCoordinate, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, int>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, DateTime>> getLowestStoredDateTime() =>
      (super.noSuchMethod(
            Invocation.method(#getLowestStoredDateTime, []),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, DateTime>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, DateTime>>(
                this,
                Invocation.method(#getLowestStoredDateTime, []),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, DateTime>>);
}
