// Mocks generated by Mockito 5.4.6 from annotations
// in jourscape/test/features/gps_tracking/presentation/providers/gps_coordinates_by_date_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fpdart/fpdart.dart' as _i5;
import 'package:jourscape/core/error/failures.dart' as _i6;
import 'package:jourscape/features/gps_tracking/domain/entities/gps_coordinate_entitiy.dart'
    as _i7;
import 'package:jourscape/features/gps_tracking/domain/repositories/gps_coordinate_repository.dart'
    as _i2;
import 'package:jourscape/features/gps_tracking/domain/use_cases/get_coordinates_by_date.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGpsCoordinateRepository_0 extends _i1.SmartFake
    implements _i2.GpsCoordinateRepository {
  _FakeGpsCoordinateRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetGPSCoordinateByDate].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetGPSCoordinateByDate extends _i1.Mock
    implements _i3.GetGPSCoordinateByDate {
  MockGetGPSCoordinateByDate() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GpsCoordinateRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeGpsCoordinateRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.GpsCoordinateRepository);

  @override
  _i4.Future<_i5.Either<_i6.Failure, List<_i7.GpsCoordinateEntity>>> call(
    DateTime? dateTime,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [dateTime]),
            returnValue:
                _i4.Future<
                  _i5.Either<_i6.Failure, List<_i7.GpsCoordinateEntity>>
                >.value(
                  _i8.dummyValue<
                    _i5.Either<_i6.Failure, List<_i7.GpsCoordinateEntity>>
                  >(this, Invocation.method(#call, [dateTime])),
                ),
          )
          as _i4.Future<
            _i5.Either<_i6.Failure, List<_i7.GpsCoordinateEntity>>
          >);
}
